[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"
  STREAMLIT_SERVER_HEADLESS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
